source "https://rubygems.org"

gem "jekyll", ">=4.2.0"
gem "jekyll-watch"
gem "jekyll-autoprefixer"
gem "execjs", "=2.7.0"
gem "jekyll-assets"
gem "jekyll-github-metadata"
gem "liquid"
gem "pygments.rb"
gem "redcarpet"
gem "rake"
gem "sass"
gem "sass-globbing"
gem "uglifier"
gem "nokogiri"
